micronaut:
  application:
    name: keyManagerGRPC

ERPITAU:
    URL:
      CONTAS:
        TODAS: ${ERPITAU_URL_CONTAS_TODAS:`http://localhost:9091/api/v1/private/contas/todas`}
        CLIENTES: ${ERPITAU_URL_CLIENTES_CONTA:`http://localhost:9091/api/v1/clientes`}
BCB:
  URL: ${BCB_URL:`http://localhost:8082/api/v1/pix/keys`}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

datasources:
  default:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:pix}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:ajudazupper}
    schema-generate: CREATE_DROP
    dialect: MYSQL
